# Generated by Django 4.2.19 on 2025-02-23 20:29

import cv_processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cv_processing", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="UploadedCV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=cv_processing.models.cv_upload_path),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        )
    ]
