# Generated by Django 4.2.19 on 2025-02-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cv_processing", "0002_uploadedcv")]

    operations = [
        migrations.AddField(
            model_name="uploadedcv",
            name="extracted_text",
            field=models.TextField(blank=True, null=True),
        )
    ]
